{% set name = "sklearn-genetic-opt" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 71d6216b64fdf3ef020bc89dd264082d67f119964e098af2b04893d7c5badf11

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - deap >=1.3.3
    - mlflow >=1.17.0
    - numpy >=1.19.0
    - python >=3.8
    - scikit-learn >=1.1.0
    - seaborn >=0.11.2
    - tensorflow >=2.0.0
    - tqdm >=4.61.1

test:
  imports:
    - sklearn_genetic
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rodrigo-arenas/Sklearn-genetic-opt
  summary: Scikit-lean models hyperparameters tuning, using evolutionary algorithms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - rodrigo-arenas
