{% set name = "sklearn-genetic-opt" %}
{% set version = "0.13.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2a6200c4f3e808cc6869bf5c4e6c1f6b69c6fc88340c359590e08fffad70eaee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77
    - wheel
  run:
    - python >={{ python_min }}
    - scikit-learn >=1.5.0
    - numpy >=1.26.0
    - deap >=1.4.0
    - tqdm >=4.60.0
    - pandas

test:
  imports:
    - sklearn_genetic
    - sklearn_genetic.callbacks
    - sklearn_genetic.schedules
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/rodrigo-arenas/Sklearn-genetic-opt
  summary: Scikit-learn models hyperparameter tuning and feature selection using evolutionary algorithms
  license: MIT
  license_file: LICENSE
  doc_url: https://rodrigo-arenas.github.io/Sklearn-genetic-opt/
  dev_url: https://github.com/rodrigo-arenas/Sklearn-genetic-opt

extra:
  recipe-maintainers:
    - goanpeca
    - rodrigo-arenas
